### ISSUE TITLE
Add `u-posFullscreen`

### ISSUE THREAD

**Issue by necolas** [suitcss/utils-position#2]
Would make an element cover the viewport, using `position:fixed` (as long as the element is not within an element that has a 3D transform). Pretty similar to `u-posAbsoluteCenter` but using `fixed`.

**Comment by simonsmith** [comment]
Do we think there is still value in adding this? Browser support has gotten quite good since

@timkelty @giuseppeg

**Comment by timkelty** [comment]
So would this be using `width: 100vw; height: 100vh` then?

**Comment by giuseppeg** [comment]
I added a similar utility at work `u-sticky` that sets `top, right, bottom, left` to `0` (I also have utilities for single directions) and it can be used with both `u-posAbsolute` and `u-posFixed`, but maybe `u-posFullscreen` is a better name.

**Comment by simonsmith** [comment]
> So would this be using width: 100vw; height: 100vh then?

Not sure how you mean? Replicating `posAbsoluteCenter` does the trick, but just change the position to `fixed`.

http://codepen.io/simonsmith/pen/wMRemG

**Comment by timkelty** [comment]
@simonsmith got it now, thanks.

If `u-posAbsoluteCenter` changes, [as proposed here](https://github.com/suitcss/utils-position/issues/4), you could use that for centering, and u-posFullscreen for top/bottom/left/right: 0 "pinning".

Proposal:
- add `u-posCenter`, setting top/bottom/left/right: 0 (not declaring a position).
- `u-posFullscreen` would "pin" as well, but with position: fixed
- `u-posAbsoluteCenter` would change to centering with top/left/transform

**Comment by simonsmith** [comment]
In your proposal would `u-posCenter` actually be misleading, because it doesn't move anything to the centre?

I like the idea of changing `u-posAbsoluteCenter` to your proposed one, and adding `u-posFullscreen` (maybe`u-posFullScreen`?) though.

**Comment by timkelty** [comment]
@simonsmith I suppose that's true.

I like `u-posFullScreen`, then.

**Comment by simonsmith** [comment]
:+1:
