### ISSUE TITLE
Dynamic u-posAbsoluteCenter (no explicit height required)

### ISSUE THREAD

**Issue by timkelty** [suitcss/utils-position#4]
What about either replacing u-posAbsoluteCenter or adding a new class that didn't require a height:

```
.u-posAbsoluteCenter {
 position: absolute !important;
 top: 50%  !important;
 left: 50%  !important;
 transform: translate(-50%, -50%) !important;
}
```

Something I always add to a project already.
Thoughts @giuseppeg @simonsmith?

**Comment by simonsmith** [comment]
I think this would be a nice upgrade.

**Comment by timkelty** [comment]
> We lose the pinning to the corners ability

Not sure I follow...you mean if you're doing height/width 100%?

**Comment by simonsmith** [comment]
As written in [this comment](https://github.com/suitcss/utils-position/blob/master/lib/position.css#L5-L9)

**Comment by timkelty** [comment]
Got it...Hmmm

**Comment by simonsmith** [comment]
> If we care about losing corner pinning

I can't think of a use case for it if `u-posFullScreen` existed, so perhaps we can replace the existing implementation
